name: nepse_pro
description: "NEPSE Portfolio Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  minio: ^3.5.8
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  app_links: ^6.3.0
